services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: bugsinkuser
      POSTGRES_PASSWORD: your_super_secret_password
      POSTGRES_DB: bugsink
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -h db
      retries: 5
      start_period: 10s
      interval: 5s
      timeout: 5s
  web:
    image: bugsink/bugsink:2
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - '80:8000'
    environment:
      SECRET_KEY: chahh4oht9gaib6kuinohxa1jaaY5yahB1aeBawouj5eiweenu
      CREATE_SUPERUSER: admin:admin
      PORT: 8000
      DATABASE_URL: postgresql://bugsinkuser:your_super_secret_password@db:5432/bugsink
      BEHIND_HTTPS_PROXY: 'true'
      BASE_URL: http://localhost:8000
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          python -c 'import requests;
          requests.get("http://localhost:8000/").raise_for_status()'
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  db-data:
