services:
  # Management container with a web-based terminal and SSH daemon
  mgm:
    image: harbor.rosti.cz/rosti-public/mgm:latest
    environment:
      TTYD_TOKEN: ${TTYD_TOKEN}
      SET_SHELL: fish # Options: bash, fish, zsh
    volumes:
    - /srv/stack:/srv/stack
    - /root/.docker/:/root/.docker/
    - /run/docker.sock:/run/docker.sock
    - /etc/shadow:/etc/shadow
    - /root/.ssh:/root/.ssh
    - /etc/ssh:/etc/ssh
    ports:
    - 1234:1234
    - 22:22
    profiles:
    - mgm
  
  mariadb:
    image: mariadb:12.0
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/99-mariadb.cnf
    ports:
      - '3306:3306'

  exporter:
    image: prom/mysqld-exporter:v0.13.0
    ports:
      - '80:9104'
    environment:
      DATA_SOURCE_NAME: root:${MARIADB_ROOT_PASSWORD}@(mariadb:3306)/
    restart: always
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - backup
    command: daemon --docker
    volumes:
      - /run/docker.sock:/run/docker.sock

  backup:
    image: harbor.rosti.cz/rosti-public/database-backup:v5
    environment:
      CONTAINER: stack-mariadb-1
      TARGET_DIR: /backup
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./mariadb-backup:/backup
      - /run/docker.sock:/run/docker.sock
    command:
      - loop
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.snapshot.schedule: "0 6,18 * * *"
      ofelia.job-exec.snapshot.command: "/backup_local.sh"
